### ISSUE TITLE
Yalp Store question

### ISSUE THREAD

**Issue by Grossdm** [kowith337/AppComplaints#1]
Hello!
I hope opening this `issue` is an acceptable way to ask a question.

FYI, I have only recently begun using the Yalp Store. I like the concept very much.

In your README, you mention using Yalp to access older versions of apps.

>Note: If you want to download older version of apps, consider to use Yalp Store and put the build number from bracket.

Could you please explain this in more detail for me?

TIA,
Doug

**Comment by kowith337** [comment]
In Yalp store (or Aurora), you need to access the `Manual Download` to open the page that allow to insert the app version.

For example, known good version of Apex Launcher, you need to fill the number in the bracket
> Known good version: 3.0.1 **(3010)** <-- The bold value, copy only number.

**Comment by Grossdm** [comment]
Excellent, thank you for the example.

I have successfully downloaded an older version now!

Doug®
